### ISSUE TITLE
The pareto variable parameter may be wrong

### ISSUE THREAD

**Issue by FereyFang** [sharan-naribole/PPBP-ns3#3]
Hi, I think that the pareto parameters  may be wrong.  Because the simulated traffic sending rate of PPBP is not equal to the theoretical formulation below. 
<img width="282" alt="image" src="https://user-images.githubusercontent.com/23692642/156167477-8d890a0b-4547-4ba4-ba79-95a1947b6f9b.png">
After reading the original paper of PPBP (_Internet Traffic Modeling and Future Technology Implications_) and the source code of Pareto distribution, I find that the scale parameter should be setted as the m_timeSlot in the code, not the  m_burstLength.

I also checked the previous implementation in this paper (_A new tool for generating realistic Internet traffic in NS-3_) and find the same problem. There is one oberservation about the code which could support me.  The variable m_timeSlot is created and calculated but never used.  It could be a simple coding mistake but have existed for a long time.

**Comment by alexplavan** [comment]
Hello there.

You are right. The value of the Pareto scale parameter is set as `m_burstLength->GetValue ()`, where `m_burstLength` is the value of the `MeanBurstTimeLength` attribute. I.e., the scale parameter is set as the mean value. For the Pareto distribution, the scale parameter can be expressed as $\mu (k-1)/k$, where $k$ is a shape parameter and $\mu$ is the mean, which is the same expression as for `m_timeSlot`.

Moreover, I searched for articles that reference this or the original implementation of PPBP for ns-3 and validate the Hurst exponent of traffic generated with it, but could not find any. I did my own research to estimate the resulting Hurst exponent for generated traffic with the aggregated variances method when different values for H attribute are set (https://github.com/Stingray42/ppbp-ns3-simulation) and got the following results:

* When the Pareto scale parameter is set to `m_timeSlot`, the resulting Hurst exponent is close to and tends to increase as the desired value grows.

* When the Pareto scale parameter is set to `m_burstLength->GetValue ()`, the resulting Hurst exponent is completely random.

I will create a pull request to fix this bug and hope that current maintainers will merge it soon.
